words = ['Cicatriz',
         'Cobertor',
         'Helicóptero',
         'Aniversário',
         'Vulcão',
         'Arco-íris',
         'Presidente da República',
         'Noiva',
         'Babar',
         'Montanha-russa',
         'Natal',
         'Luz',
         'Sombra',
         'Magia',
         'Maquiadora',
         'Shopping',
         'Berço',
         'Medir',
         'Espelho',
         'Aranha',
         'Moto',
         'Jardim',
         'Trampolim',
         'Cachoeira',
         'Iô-iô',
         'Janela',
         'Girafa',
         'Roncar',
         'Pesadelo',
         'Lanterna',
         'Curiosidade',
         'Panquecas',
         'Aplicativo',
         'Convite',
         'Adolescente',
         'Satélite',
         'Jornal',
         'Diamante',
         'Lenha',
         'Sapo',
         'Andador infantil',
         'Ração',
         'Google',
         'Tocha',
         'Acampar',
         'Lago',
         'Emagrecer',
         'Fofoca',
         'Salário',
         'Sorte']

invalid_letters = ['á', 'à', 'ã', 'â', 'ä', 'é', 'è', 'ê', 'ë', 'í', 'ì', 'î', 'ï', 'ó', 'ò', 'õ', 'ô', 'ö', 'ú',
                 'ù', 'û', 'ü', 'Á', 'À', 'Ã', 'Â', 'Ä', 'É', 'È', 'Ê', 'Ë', 'Í', 'Ì', 'Î', 'Ï', 'Ó', 'Ò', 'Õ',
                 'Ô', 'Ö', 'Ú', 'Ù', 'Û', 'Ü']
